# Generated by Django 3.2 on 2021-06-09 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='Task',
            new_name='task',
        ),
    ]
