# Generated by Django 3.2 on 2021-06-09 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_task_activity_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='task',
            new_name='title',
        ),
    ]
